### ISSUE TITLE
Player - Log In to View Player Stats

### ISSUE THREAD

**Issue by usamike25** [sopra-fs24-group-33/server#1]
**User Story:**

As a Player, I want to be able to log in to my already created account, so I can see my player stats.

**Acceptance Criteria:**

- [ ] The player can choose to log in with their (unique) username and password.
- [ ] Upon successful login, move to the overview page.

**Priority:** High

**Author:** Miguel

**Estimate:** 8h

**Development Tasks:**

- [ ] sopra-fs24-group-33/server#20
- [ ] sopra-fs24-group-33/client#27
- [x] sopra-fs24-group-33/server#22
- [ ] sopra-fs24-group-33/client#28
- [ ] sopra-fs24-group-33/client#26
