### ISSUE TITLE
Players - Shared View of Game Arena

### ISSUE THREAD

**Issue by usamike25** [sopra-fs24-group-33/server#122]
**User Story:**

As a Player, I want all players in the game to see the same game arena so that we can monitor the state of the game together.

**Acceptance Criteria:**

- [x] Each player gets cards from the deck depending on the level.
- [x] You see your own card.
- [x] You see the covered cards of the others and how many they have.
- [x] You see which card belongs to which person.
- [x] The most recent card played is visible in the middle of the table.
- [x] Game information such as level and number of cards is displayed.

**Priority:** Very High

**Author:** Paulin

**Estimate:** 20h (research not included)

**Development Tasks:**

- [x] sopra-fs24-group-33/client#8
- [x] sopra-fs24-group-33/server#59
- [x] sopra-fs24-group-33/server#60
- [ ] sopra-fs24-group-33/client#7
