### ISSUE TITLE
Player - Receive Feedback on Played Cards

### ISSUE THREAD

**Issue by usamike25** [sopra-fs24-group-33/server#14]
**User Story:**

As a Player, when I play a card, I want to know whether it was the right one to advance in the game.

**Acceptance Criteria:**

- [ ] A visible indication of whether the card played was correct.
- [ ] Round indicators are correctly updated.
- [ ] The outcome (positive or negative) is clearly communicated.

**Priority:** High

**Author:** Valentin

**Estimate:** 15h

**Development Tasks:**

- [ ] sopra-fs24-group-33/server#65
- [ ] sopra-fs24-group-33/client#15
- [ ] sopra-fs24-group-33/client#4
