### ISSUE TITLE
New Player - Register to Save Progress

### ISSUE THREAD

**Issue by usamike25** [sopra-fs24-group-33/server#2]
**User Story:**

As a New Player, I want to be able to register for an account so that I can save my progress and access potential player-only features.

**Acceptance Criteria:**

- [ ] The player can navigate to the registration screen from the login screen.
- [ ] The player must provide a unique username and a password to create a new account.
- [ ] The system validates the information and displays an error message if the username is already taken or the password doesn't meet the security requirements.
- [ ] Upon successful registration, the player is automatically logged in and taken to the main game screen.

**Priority:** High

**Author:** Miguel

**Estimate:** 8h

**Development Tasks:**

- [ ] sopra-fs24-group-33/client#23
- [x] sopra-fs24-group-33/server#28
- [ ] sopra-fs24-group-33/server#27
- [x] sopra-fs24-group-33/server#26
- [x] sopra-fs24-group-33/client#25
