### ISSUE TITLE
Visitor - Log In as Guest to Try Game

### ISSUE THREAD

**Issue by usamike25** [sopra-fs24-group-33/server#3]
**User Story:**

As a Visitor, I want to be able to log in as a guest so that I can try the game without registering.

**Acceptance Criteria:**

- [ ] Guest players' progress is not saved after they log out.
- [ ] Guest players are informed about the limitations and given the option to register for a full account.
- [ ] Upon selecting the guest login option, the player is taken immediately to the main game screen to start playing.

**Priority:** High

**Author:** Miguel

**Estimate:** 8h

**Development Tasks:**

- [ ] sopra-fs24-group-33/client#19
- [x] sopra-fs24-group-33/server#32
- [ ] sopra-fs24-group-33/client#22
- [ ] sopra-fs24-group-33/client#24
