### ISSUE TITLE
Player - Overview of All Users for Stats Retrieval

### ISSUE THREAD

**Issue by usamike25** [sopra-fs24-group-33/server#4]
**User Story:**

As a Player, I want to see an overview of all users so that I can retrieve player stats like the number of games played and number of shame tokens collected.

**Acceptance Criteria:**

- [ ] Only guests and logged-in users can access the overview.
- [ ] There is a Create Lobby and Join Lobby button that navigates the player to the corresponding page.

**Priority:** High

**Author:** Kavishan

**Estimate:** 10h

**Development Tasks:**

- [x] sopra-fs24-group-33/client#17
- [x] sopra-fs24-group-33/server#36
- [x] sopra-fs24-group-33/client#20
- [x] sopra-fs24-group-33/client#21
