### ISSUE TITLE
Player - Access Rules for Better Game Understanding

### ISSUE THREAD

**Issue by usamike25** [sopra-fs24-group-33/server#5]
**User Story:**

As a Player, I want to be able to look up the rules of the game so that I know how to play.

**Acceptance Criteria:**

- [ ] There is a button which reveals game rules.
- [ ] Game rules are retrievable any time (in the overview, lobby, in-game).

**Priority:** Low

**Author:** Valentin & Kavishan

**Estimate:** 5h

**Development Tasks:**

- [x] sopra-fs24-group-33/client#12
- [ ] sopra-fs24-group-33/client#16
- [x] sopra-fs24-group-33/client#18

**Comment by kauii** [comment]
client side features
