### ISSUE TITLE
User - Create a Lobby with Game Mode Selection

### ISSUE THREAD

**Issue by usamike25** [sopra-fs24-group-33/server#6]
**User Story:**

As a User, I want to be able to create a lobby, and as an extra feature, be able to choose the game mode.

**Acceptance Criteria:**

- [ ] When creating a lobby, the player has to give a name to it.
- [ ] Only guests and registered users can create a lobby.

**Priority:** High

**Author:** Valentin & Kavishan

**Estimate:** 20h (without the game mode)

**Development Tasks:**

 - [x] sopra-fs24-group-33/client#9
 - [x] sopra-fs24-group-33/server#43
 - [ ] sopra-fs24-group-33/server#42
 - [x] sopra-fs24-group-33/server#41
